### ISSUE TITLE
Less e-mail spam from e2e test failures

### ISSUE THREAD

**Issue by eparis** [kubernetes/test-infra#1723]
At the moment if a PR doesn't build or has some other major problem it will fail all of the e2e tests. The bot will create a new comment for every single failure. That new comment will have the summarization of all test failures for the commit, but it still creates a new comment and deletes the old. This means I get ~8 emails. Even though the github history looks good.

Personally I'd rather get 1 e-mail for each pull that failed. And have that first comment edited with all the info. If a new push is bad the first failure should create a new comment (delete any old comments) and will generate an e-mail. If a following test fails the bot should update that comment rather than create new/delete.

Doing so would cut way down on e-mail spam. Admittedly it would lose some e-mail fidelity as you wouldn't get all test failures in your e-mail, only the first. But it seems like a good tradeoff to me.

1 email per push.

**Comment by eparis** [comment]
@spxtr

**Comment by spxtr** [comment]
I think it was @thockin who likes the email spam. Maybe he can weigh in?

**Comment by thockin** [comment]
I can live with that.  Maybe include "this comment may be updated if other tests fail" ?

**Comment by liggitt** [comment]
+1 for new comment on aggregate state change, updating comment otherwise

**Comment by thockin** [comment]
So what I am seeing now is that a PR is updated with over TWENTY new
comments just from teh test bot.  Can we go back to just editing the
comment? :)

**Comment by spxtr** [comment]
Yep, I can do that. The reason you're seeing extra emails is because it removes the entry when the test passes.

**Comment by spxtr** [comment]
Another idea, I can also make it only send an email if a new failure shows up, and edit the comment to remove passing tests.

**Comment by eparis** [comment]
I admit, I'm still big on one e-mail per push...

**Comment by spxtr** [comment]
OK, right now it does one email per failure, the same behavior as before. I did it that way just because it was an easy improvement, but we can still make it approximate one email per push.

**Comment by thockin** [comment]
If the emails restarted on a new push, I would be OK .  As it is, a WIP PR
has something like 75 bot comments.

**Comment by spxtr** [comment]
See issue #1962 by @resouer.

**Comment by resouer** [comment]
Yes, my two cents is maybe we can just send test failure emails to the PR author, not every participant. :)

**Comment by fejta** [comment]
I like the #1962 format

**Comment by fejta** [comment]
/assign @spxtr 

Are we done/happy here for now?

**Comment by spxtr** [comment]
I improved it, but I think we should leave this open for now. We still send an email for every failure, not for every commit with a failure.

**Comment by fejta** [comment]
Requires modifying https://github.com/kubernetes/test-infra/blob/547f449510b61b012485c4d58070aafab00a86ce/prow/report/report.go#L82

**Comment by matthyx** [comment]
@fejta I don't quite understand what should be changed in report.go do you want to keep on creating/updating/removing report on failure, and get an aggregated error at the end of `Report()`?

**Comment by BenTheElder** [comment]
cc @krzyzacy what about doing this with the new reporter tooling? less email spam sounds amazing :^)

**Comment by krzyzacy** [comment]
cc @neolit123 who just asked today 
/pony spam

**Comment by neolit123** [comment]
i can take a look at this.

/assign
/remove-help
/priority important-longterm

**Comment by krzyzacy** [comment]
My $0.02 here:

Currently we call into reportlib from places like: plank, jenkins-operator, external-plugins/refresh/server.go and crier, I'm working on move it out of plank to crier, unclear if I want to handle other ones in the same time yet.

I've implemented the aggregate report behavior for gerrit in https://github.com/kubernetes/test-infra/blob/master/prow/gerrit/reporter/reporter.go#L100 but that's pretty bespoke, since we don't allow retest in gerrit, I think on top of that we also need to figure out the most recent job per PR.

Also we probably want to chat with contribex per https://github.com/kubernetes/community/blob/master/sig-testing/charter.md#cross-cutting-and-externally-facing-processes

**Comment by neolit123** [comment]
gathering bits from some old comments in this threads and from our discussion today.

i think this is the culprit of the problem:
https://github.com/kubernetes/test-infra/issues/1723#issuecomment-292085934
> We still send an email for every failure, not for every commit with a failure.

from my limited understanding of the infrastructure i can think of a solution how to handle this with a generic GitHub bot client - here is what i think can be done:
- when there is an initial failure make the bot write a comment (with the table, as it is doing now).
- when a new failure happens verify if it's against the same commit (e.g. the commit for a failure is already known / written in the table):
-- if yes, update the old comment.
-- if not, delete the old comment and create a new one.

would that work?

one potenial problem with the above:
if a discussion happens it can push the bot table report up the history. if that's the case we can delete the old comment and create a new one too.

but honestly, the PR status at the bottom is also a pretty good source of truth. it turns orange / red if something fails and it that and the table kind of duplicate GUI, in a way.

> Also we probably want to chat with contribex per https://github.com/kubernetes/community/blob/master/sig-testing/charter.md#cross-cutting-and-externally-facing-processes

cc @kubernetes/sig-contributor-experience-bugs 
cc @tpepper

**Comment by fejta** [comment]
One issue with the current table is that when I push a new commit, it will still show me failures from the old commit while those jobs are still running. 

Ideally when we detect a new commit we clear the table and only show failures for that commit.

**Comment by Katharine** [comment]
The fix for this was reverted due to lack of consensus.

**Comment by alvaroaleman** [comment]
Any chance we can re-introduce the "skip updating comments when a ProwJob is for an old commit." part of #11341 together with a feature gate so users other than prow.k8s.io can disable this weirdness?

**Comment by BenTheElder** [comment]
said irony fejta-bot :(
