### ISSUE TITLE
Jenkins 'frequency' not working as intended

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/test-infra#3977]
I recently noticed that one of the kubemark tests scheduled to run once every week (https://github.com/kubernetes/test-infra/blob/master/jenkins/job-configs/kubernetes-jenkins/bootstrap-ci.yaml#L257) is actually running everyday - https://k8s-testgrid.appspot.com/sig-scalability#kubemark-100-high-density. Something seems to be wrong with the frequency.

Also I recently automated our scalability tests (in PR https://github.com/kubernetes/test-infra/pull/3943), however seems like it wasn't triggered (and I had to manually start it).

cc @krzyzacy @fejta @gmarek

**Comment by krzyzacy** [comment]
/assign @rmmh  @ixdy 
who might know more about Jenkins cron string...

**Comment by rmmh** [comment]
The trigger-job line makes it run after every build. This is silly.

**Comment by rmmh** [comment]
This should all be fixed now.

**Comment by fejta** [comment]
Migrate to prow

**Comment by rmmh** [comment]
Prow doesn't actually support the sort of interleaved scheduling they're using here.

**Comment by shyamjvs** [comment]
Thanks a lot for fixing the issue @rmmh.

> Prow doesn't actually support the sort of interleaved scheduling they're using here (yet).

That's right. Precisely the point I've been saying for a while :)

**Comment by fejta** [comment]
I do not consider interleaved scheduling a useful/productive pattern (flexible and prone to problems). I consider this an edge case whose complexity we ideally keep out of prow.

I see no innate need for interleaved scheduling. Instead I see multiple jobs needing exclusive access to the same resource. There are a variety of ways to address this need without adding weight to prow.

A couple examples:
* Chaining the jobs with `run_after_success` in prow guarantees the jobs will not run at the same time.
* Complicated scheduling logic can use a custom scheduling controller.

**Comment by fejta** [comment]
Our goal with test-infra is more to help guide teams towards simpler, more productive patterns as it is to cater to every whim and feature request.

**Comment by rmmh** [comment]
This could also be handled with a 1-week interval and the job being a member of a group with a concurrency limit of 1.

**Comment by fejta** [comment]
That sounds like a pretty clean design. Although I believe a 1w interval right now is equivalent to daily (prow doesn't remember more than a day, or maybe we fixed that)

**Comment by rmmh** [comment]
We could change Sinker's deletion rule to not delete the most recent run for a job if it's under a month old, which would allow long intervals without affecting higher-throughput jobs.

**Comment by shyamjvs** [comment]
I agree that we should aim for simpler and productive patterns. However I'd like to re-emphasize the following (we had discussed this earlier as well):

> I do not consider interleaved scheduling a useful/productive pattern (flexible and prone to problems).

It is indeed quite flexible, but I don't see how it is prone to problems. We have been using crontabs in linux for a long long time and I think it's well-accepted by now that it is a very robust, ,flexible and expressive language for scheduling periodic jobs. Jenkins (with multiple years of expertise in CI/CD) supports it for a good reason. Besides, what crontab offers is so useful that it was compelling enough to have it implemented in k8s. Also note that crontab is a superset of prow which currently only allows specifying frequency (i.e jobs can only be run 'once per every X hours' which is far from the flexibility cron offers). We even discussed this earlier and spxtr@ also agreed that with all the tooling available in k8s already this isn't super hard to do - https://github.com/kubernetes/test-infra/issues/3774#issuecomment-319147704.

> I consider this an edge case whose complexity we ideally keep out of prow.

This wasn't considered an edge case back when we were using jenkins when crontabs were being used. And to be honest I'm not very convinced why you consider crontabs a complexity. We agreed earlier that it shouldn't really be so complex to do this (https://github.com/kubernetes/test-infra/issues/3774). Besides it's a paradigm k8s already offers us :)

> I see no innate need for interleaved scheduling.

Yes we use interleaving in scale-tests, but this is not just about interleaving. I can imagine someone wanting to run their test once every thursday (potentially because they want to test the changes made along mon-wed and to keep friday for debugging).

>  Instead I see multiple jobs needing exclusive access to the same resource.

That's true, there are multiple jobs needing the project quota available. Though they're not exactly competing jobs. Each one has it's own designated day of the week which already ensures exclusivity. However the main reason to assign days is not to make them exclusive but other considerations that I mentioned in https://github.com/kubernetes/test-infra/issues/3774#issuecomment-318735144

> Chaining the jobs with run_after_success in prow guarantees the jobs will not run at the same time.

Again, the requirement here is not to solve the problem of race between the jobs (that is automatically ensured by designating days), it's about timing them on specific days. For e.g the 5000-node performance test on gce is a release-blocking test and needs to be run more than once a week, but on alternate weekdays (to give time for SIGs to debug any failures relevant).

> Complicated scheduling logic can use a custom scheduling controller.

We should be able to reuse k8s cronjobs (which [prowjobs seem to be similar to internally](https://github.com/kubernetes/test-infra/issues/3774#issuecomment-319147704)) rather than writing custom controller each time someone needs it.

**Comment by shyamjvs** [comment]
That said, I agree with @rmmh 's suggestion for scheduling jobs weekly. However the period-based approach still doesn't allow us to say things like "run on monday and thursday of each week".

**Comment by shyamjvs** [comment]
Btw - I'm looking forward to actually moving as many of the scalability jobs as possible to prow. For e.g all kubemark and (gce|gke)-scalability jobs can be moved to prow currently (which is quite a good news already). What remain are the 'real' scalability tests (2k-node and 5k-node ones) which are critical to the release and hence need good reliability.

**Comment by shyamjvs** [comment]
And regarding the 'run_after_success' suggestion, there're few catches there (let me know of some of them aren't true):
- We need to be able to run even after failure
- This can lead to a situation where a 5000-node job runs on a weekend due to the jobs preceeding it pushing it backward over time (while it should run on a weekday for safety)
- They are not running in a cycle with each job exactly once (like A -> B -> C -> D -> A ...), but instead some important ones run more frequently (like A -> B -> A -> C -> A ..)

**Comment by shyamjvs** [comment]
just fyi - @ignacyk
